version: '2.1'

services:
  dish:
    build: microservices/dish-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_DATABASE=dish-db
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  order:
    build: microservices/order-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_DATABASE=order-db
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  restaurant:
    build: microservices/restaurant-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_DATABASE=restaurant-db
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    mem_limit: 350m
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
