server.port: 7000
server.error.include-message: always

app:
  restaurant-service:
    host: localhost
    port: 7001
  dish-service:
    host: localhost
    port: 7002
  order-service:
    host: localhost
    port: 7003


logging:
  level:
    root: INFO
    io.github.marbys: DEBUG


spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    output-dishes:
      destination: dishes
      producer:
        required-groups: auditGroup
    output-orders:
      destination: orders
      producer:
        required-groups: auditGroup
    output-restaurants:
      destination: restaurants
      producer:
        required-groups: auditGroup

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile: docker

server.port: 8080

app:
  restaurant-service:
    host: restaurant
    port: 8080
  dish-service:
    host: dish
    port: 8080
  order-service:
    host: order
    port: 8080

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka
