server:
  error.include-message: always
  port: 7003

logging:
  level:
    root: INFO
    io.github.marbys: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: order-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: orders
    group: ordersGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

spring:
  data:
    mongodb:
      auto-index-creation: true
---

spring:
  config:
    activate:
      on-profile: docker

spring.data.mongodb.host: mongodb

server.port: 8080

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka
