server:
  error.include-message: always
  port: 7003

spring.datasource:
  url: jdbc:mysql://localhost/order-db?useTimezone=true&serverTimezone=UTC
  username: root
  password: admin

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
---

spring:
  config:
    activate:
      on-profile: docker

spring.datasource:
  url: jdbc:mysql://mysql/order-db

server.port: 8080
