server:
  error.include-message: always
  port: 7001

spring.datasource:
  url: jdbc:mysql://localhost/restaurant-db?useTimezone=true&serverTimezone=UTC
  username: root
  password: admin

spring:
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: restaurants
    group: restaurantsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---

spring:
  config:
    activate:
      on-profile: docker

spring.datasource:
  url: jdbc:mysql://mysql/restaurant-db

server.port: 8080
