server:
  port: 7002
  error.include-message: always

spring.datasource:
  url: jdbc:mysql://localhost/dish-db?useTimezone=true&serverTimezone=UTC
  username: root
  password: admin
  initialization-mode: always


spring.jpa:
    hibernate:
      ddl-auto: create

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: dishes
    group: dishesGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    io.github.marbys: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    password: pwd
    url: jdbc:mysql://mysql/dish-db
    username: user

server.port: 8080

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka


